# Generated by Django 3.1.6 on 2021-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mode',
            field=models.BooleanField(default=False),
        ),
    ]
