# Generated by Django 3.1.6 on 2021-02-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mode',
            new_name='public',
        ),
    ]
